/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simulation_py4j;

import py4j.GatewayServer;

public class App {

    private SynchronousSimulationExample1 stack;

    public App() {
      stack = new SynchronousSimulationExample1();
    }

    public SynchronousSimulationExample1 getStack() {
        return stack;
    }

    public static void main(String[] args) {
        GatewayServer gatewayServer = new GatewayServer(new App());
        gatewayServer.start();
        System.out.println("Gateway Server Started");
    }


}
