apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name:  grafanadatasources.dcna.dev
spec:
  group: dcna.dev
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                base_url:
                  type: string
                tokenSecretRef:
                  type: object
                  properties:
                    name:
                      type: string
                    key:
                      type: string
      additionalPrinterColumns:
        - name: Base URL
          type: string
          description: Base URL for Grafana Datasource
          jsonPath: .spec.base_url
        - name: Token Secret Name
          type: string
          description: Secret name that contains the token
          jsonPath: .spec.tokenSecretRef.name        
  scope: Namespaced
  names:
    plural: grafanadatasources
    singular: grafanadatasource
    kind: GrafanaDatasource
    shortNames:
      - gds