apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name:  monitors.dcna.dev
spec:
  group: dcna.dev
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                frequency:
                  type: string
      additionalPrinterColumns:
        - name: Frequency
          type: string
          description: Monitor frequency
          jsonPath: .spec.frequency
  scope: Namespaced
  names:
    plural: monitors
    singular: monitor
    kind: Monitor
    shortNames:
      - mo